---
- name: Setup rapid
  hosts: rapid
  vars:
    repos_www_root: /var/www/repos
    playbook_repo_url: https://github.com/p2004a/rapid-hosting.git
  tasks:
  - name: Set up HTTP server for repos
    include_role:
      name: http_server
    vars:
      site_name: repos
      domain_name: '{{ repos_domain_name }}'
      serving_root: '{{ repos_www_root }}'
  - name: Create index file
    ansible.builtin.copy:
      dest: '{{ repos_www_root }}/index.html'
      content: '{{ repos_domain_name }}'
  - name: Set up rapid repos syncer
    include_role:
      name: rapid_repos
    vars:
      domain_name: '{{ repos_domain_name }}'
      www_root: '{{ repos_www_root }}'
  - name: Set up ansible-pull
    include_role:
      name: ansible_pull
    tags: ansible_pull
