---
# matching from inventory happens based on hostname when executing ansible pull
- name: Set hostname
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'
- name: Replace a 127.0.1.1 entry with new hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ inventory_hostname }}'
- name: Install ansible
  ansible.builtin.package:
    state: present
    name:
    - ansible
- name: Install ansible-pull.timer file
  ansible.builtin.copy:
    src: files/ansible-pull.timer
    dest: /etc/systemd/system/ansible-pull.timer
  notify: Reload systemd
- name: Install ansible-pull.service file
  ansible.builtin.template:
    src: templates/ansible-pull.service.j2
    dest: /etc/systemd/system/ansible-pull.service
- name: Enable systemd ansible-pull timer
  ansible.builtin.systemd:
    name: ansible-pull.timer
    state: started
    enabled: yes
