---
- name: Check repo name is only alphanum and dashes
  assert:
    that: repo.name is match('^[a-z0-9-]+$')
    quiet: true
- name: Set up repo {{ repo.name }}
  include_tasks: repo-present.yml
  when: repo.state | default('present') == 'present'
- name: Remove repo {{ repo.name }}
  include_tasks: repo-absent.yml
  when: repo.state | default('present') == 'absent'
