---
- name: Set repo {{ repo.name }} config
  ansible.builtin.copy:
    dest: '{{ config_root }}/repo-{{ repo.name }}.json'
    # state only drives this role, it's not a part of the repo definition.
    content: "{{ repo | dict2items | rejectattr('key', 'eq', 'state') | items2dict | to_json(indent=4, sort_keys=True) }}"
- name: Fetch {{ repo.name }} git repository
  ansible.builtin.git:
    dest: '{{ git_root }}/{{ repo.name }}'
    repo: '{{ repo.origin }}'
    single_branch: true
    update: no
    version: "{{ repo.branch }}"
- name: Create www repo directory
  ansible.builtin.file:
    state: directory
    path: '{{ www_root }}/{{ repo.name }}'
- name: Enable systemd timer for updating {{ repo.name }}
  ansible.builtin.systemd:
    # replace simulated systemd-escape for the single allowed character needing it
    name: "update-rapid-repo@{{ repo.name | replace('-', '\\x2d') }}.timer"
    state: started
    enabled: yes
