---
- name: Install dependencies
  ansible.builtin.package:
    state: present
    name: caddy
- name: Create site root directory
  ansible.builtin.file:
    state: directory
    path: '{{ serving_root }}'
- name: Set up caddy config
  ansible.builtin.template:
    src: templates/Caddyfile.j2
    dest: /etc/caddy/Caddyfile
  notify: Reload caddy
